'use client'
import { useState } from "react"

const API = process.env.NEXT_PUBLIC_API_URL

function renderMarkdown(text: string) {
  return text.split('\n').map((line, i) => {
    if (!line.trim()) return <div key={i} className="h-3" />
    if (line.startsWith('# ')) {
      return <h2 key={i} className="text-lg font-bold text-slate-900 mt-5 mb-2">{line.slice(2)}</h2>
    }
    if (line.startsWith('## ')) {
      return <h3 key={i} className="text-base font-semibold text-slate-800 mt-4 mb-1">{line.slice(3)}</h3>
    }
    const parts = line.split(/\*\*(.*?)\*\*/g)
    const rendered = parts.map((part, j) =>
      j % 2 === 1
        ? <strong key={j} className="font-semibold text-slate-900">{part}</strong>
        : part
    )
    if (line.match(/^\d+\./)) {
      return (
        <div key={i} className="flex gap-2 text-sm text-slate-700 leading-relaxed">
          <span className="text-slate-400 flex-shrink-0">{line.match(/^\d+/)?.[0]}.</span>
          <span>{rendered.slice(1)}</span>
        </div>
      )
    }
    return <p key={i} className="text-sm text-slate-700 leading-relaxed">{rendered}</p>
  })
}

const StatCard = ({ value, label, color }: { value: any; label: string; color: string }) => (
  <div className="bg-slate-50 rounded-xl p-5 text-center border border-slate-100">
    <p className={`text-3xl font-bold ${color}`}>{value}</p>
    <p className="text-xs text-slate-400 mt-1.5 font-medium">{label}</p>
  </div>
)

export default function SummaryPage() {
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    setLoading(true)
    const r = await fetch(`${API}/analytics/summary`)
    setData(await r.json())
    setLoading(false)
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Executive Summary</h1>
          <p className="text-sm text-slate-400 mt-1">AI-generated weekly ops report · ready for leadership</p>
        </div>
        <button
          onClick={generate}
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2.5 bg-slate-900 text-white text-sm font-semibold rounded-lg hover:bg-slate-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? (
            <>
              <span className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            <>⚡ Generate weekly summary</>
          )}
        </button>
      </div>

      {!data && !loading && (
        <div className="flex flex-col items-center justify-center py-24 border-2 border-dashed border-slate-200 rounded-xl bg-slate-50">
          <div className="text-4xl mb-4">📊</div>
          <p className="text-sm font-semibold text-slate-600">No summary generated yet</p>
          <p className="text-xs text-slate-400 mt-1">Click the button above to generate a weekly executive report</p>
        </div>
      )}

      {data && (
        <>
          {/* Stats */}
          <div className="grid grid-cols-3 gap-3">
            <StatCard value={data.stats.total_tickets} label="Total tickets" color="text-slate-900" />
            <StatCard value={data.stats.escalated} label="Escalated" color="text-red-600" />
            <StatCard value={data.stats.resolved} label="Resolved" color="text-emerald-600" />
          </div>

          {/* Narrative */}
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50">
              <div>
                <p className="text-sm font-semibold text-slate-700">Weekly operations narrative</p>
                <p className="text-xs text-slate-400 mt-0.5">Generated by claude-haiku-4-5 · for COO / VP Ops</p>
              </div>
              <span className="text-xs text-slate-400">
                {new Date(data.generated_at).toLocaleString()}
              </span>
            </div>
            <div className="px-6 py-5 space-y-1">
              {renderMarkdown(data.summary)}
            </div>
          </div>

          {/* Category breakdown */}
          {data.stats.by_category && (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5">
              <p className="text-sm font-semibold text-slate-700 mb-3">Category breakdown</p>
              <div className="grid grid-cols-2 gap-2">
                {Object.entries(data.stats.by_category).map(([cat, count]) => (
                  <div key={cat} className="flex items-center justify-between bg-slate-50 rounded-lg px-3 py-2">
                    <span className="text-xs font-medium text-slate-600 capitalize">{cat.replace("_", " ")}</span>
                    <span className="text-xs font-bold text-slate-800">{count as number}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  )
}
